FROM debian:jessie

LABEL maintainer s5550055.minimum@gmail.com

RUN apt-get -qq update \
  && apt-get -qq -y install vim python3 python3-pip jq groff >/dev/null \
  && pip3 install -q awscli

ENTRYPOINT ["/usr/local/bin/aws"]
