FROM alpine

LABEL maintainer s5550055.minimum@gmail.com

RUN apk --no-cache -q add python3 curl bash jq groff \
  && (curl https://bootstrap.pypa.io/get-pip.py | python3) \
  && pip3 install -q awscli \
  && apk del curl

ENTRYPOINT ["/usr/bin/aws"]
