FROM alpine

LABEL maintainer s5550055.minimum@gmail.com

RUN apk --no-cache add python3 curl bash \
  && (curl https://bootstrap.pypa.io/get-pip.py | python3) \
  && pip3 install awscli boto3 \
  && apk del curl

ENTRYPOINT ["/bin/aws"]
